s3:
  endpoint_url: "https://objectstore.e2enetworks.net"
  aws_access_key_id: "6SE0BP2TKXZKE7V59442"
  aws_secret_access_key: "M7N80RP5ZUNPIRJQ7R46PDYATKHYUXF8F7E5FO7I"
  region_name: "us-east-1"
  bucket: "gcode-to-be-executed"
  machineid : "C42"

local:
  download_folder: "gcodes"
  state_file: "./.s3_downloader_state.json"
  sync_state_file: "./sync_state.json" 
polling:
  interval_seconds: 5
  max_retries: 5
  backoff_factor: 2