version: '3.8'

services:
  humac:
    build:
      context: .
      dockerfile: Dockerfile.ARM
    container_name: Humac_driver_gcode
    image: humac_image_gcode
    restart: unless-stopped
    privileged: true
    network_mode: host
    depends_on:
      - redis
    volumes:
      - ./:/humac
    
    logging:
      driver: "json-file"
      options:
        max-size: "20m"

  redis:
    image: redis:7-alpine
    container_name: redis_database
    restart: always
    network_mode: host
    volumes:
      - redis-data:/data
    command: >
      redis-server 
      --appendonly yes 
      --appendfsync everysec
      --auto-aof-rewrite-percentage 100
      --auto-aof-rewrite-min-size 64mb
      --maxmemory 256mb 
      --maxmemory-policy allkeys-lru
      --save 60 1000  
      --save 300 100
      --dir /data
    logging:
      driver: "json-file"
      options:
        max-size: "10m"

volumes:
  redis-data: